# Basic
title: 张林
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: 张林
# 头像里面的描述
avatarDesc: 学习/听歌/打游戏
url: "https://zhanglin.space"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
  # gitalk: true
  # clientID: '9011b0d4482b2d4839ff'
  # secret: '6d7160f76a65ecc330e55090f50072ccdc8aca6e '
  # repo: 'zhanglin233.github.io'
  # ower: 'zhanglin233'
  # admin: 'zhanglin233'
  # distractionFreeMode: true

    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 5366874726
    github: zhanglin233
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter:
    # mail: leopardpan@icloud.com


# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: 649253cb0e49b58d83ffa37b2efe3cd9



# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 技术支持, description: support, url: '/support'}
    - {title: 关于我, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
